export const themes = [
    {
        name: 'dark',
        backgroundPrimary: '#1a1a1a',
        primary: '#f2f2f2',
        secondary: '#808080',
        alternate: '#262626',
        textPrimary: '#f2f2f2',
        error: '#bf0000',
    },
    {
        name: 'light',
        backgroundPrimary: '#f2f2f2',
        primary: '#1a1a1a',
        secondary: '#767676',
        alternate: '#c2c2c2',
        textPrimary: '#1a1a1a',
        error: '#dd1c1c',
    },
    {
        name: 'catppuccin',
        backgroundPrimary: '#1e1e2e',
        primary: '#cba6f7',
        secondary: '#7f849c',
        alternate: '#181825',
        textPrimary: '#cdd6f4',
        error: '#f38ba8',
        // positive: '#A3D9B1',
    },
    {
        name: "koopa beach",
        backgroundPrimary: '#fffffe',
        primary: '#ff9d00',
        secondary: '#565b6e',
        alternate: '#bae8e8',
        textPrimary: '#272343',
        error: '#dd3322',
    },
    {
        name: 'sonokai',
        backgroundPrimary: '#222327',
        primary: '#ff6077',
        secondary: '#595f6f',
        alternate: '#33353f',
        textPrimary: '#e2e2e3',
        error: '#fc5d7c',
    },
    {
        name: "arc",
        backgroundPrimary: '#383c4a',
        primary: '#5294e2',
        secondary: '#d3dae3',
        alternate: '#404552',
        textPrimary: '#f5f6f7',
        error: '#fc4138',
    }
];